### ISSUE TITLE
Exibir na lista de candidaturas aquelas que ainda não responderam nenhuma questão

### ISSUE THREAD

**Issue by lguima** [Minhacps/votacidade-app#117]
## **Aplicação**
- App - [`Minhacps/votacidade-app`](https://github.com/Minhacps/votacidade-app)

## **Critérios de aceite**
Liste os critérios que definirão quando a estória estará completa.

- Acessibilidade garantida
- Responsividade garantida
- Exibir as candidaturas que se cadastraram, mas ainda não responderam nenhuma questão

## **Tarefas**
- [ ] Atualizar a condição da query de filtro da página de candidaturas

**Comment by victormiguez** [comment]
@lguima podemos fechar essa issue?
