### ISSUE TITLE
Exibir a justificativa dos candidatos na página do perfil. 

### ISSUE THREAD

**Issue by wab030** [Minhacps/votacidade-app#125]
## **Aplicação**
A qual aplicação a tarefa está relacionada?
- App - [`Minhacps/votacidade-app`](https://github.com/Minhacps/votacidade-app)

## **Descrição**
Exibir a justificativa dos candidatos na página do perfil.

**Comment by notnotgabriel** [comment]
@wab030 estou fechando esta issue porque já implementamos
<img width="335" alt="image" src="https://user-images.githubusercontent.com/5247142/96951766-98d1da00-14c3-11eb-94f2-b5b306f7ca05.png">
