### ISSUE TITLE
Informar usuário que pode receber notificações da Minha Cidade

### ISSUE THREAD

**Issue by victorperin** [Minhacps/votacidade-app#142]
Como Minha Campinas, gostaria de perguntar aos usuários se deseja receber informações do Minha Cidade por e-mail ou celular.

Depois que finalizar o questionário, apresentar ao usuário se deseja receber informações da Minha Cidade pelo e-mail ou celular

**Comment by wab030** [comment]
Já está escrito na política de privacidade.
